# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HIGjzxaObU_on70Aq04kkI4zZgWx8p2q
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/My Drive/PRSA_Data_Changping_20130301-20170228.csv")

df.describe

df1 = df.dropna()
print(df1)

"""df1 = df.drop_duplicates(subset='month', keep='first')"""

print(df1)

df1.head

df1

#Temperature(degree Celsius) by CO(Carbon Monoxide) concentration (ug/m^3)
X = df1.iloc[:, 11]
Y = df1.iloc[:, 9]
plt.scatter(X, Y)
plt.show()

m = 0
c = 0
L = 0.0001 #learning rate
n = float(len(X)) #elements in X

for i in range(1000): #For loop for gradient descent 
    Y_pred = m*X + c  #y=mx+b to find the predicted value of Y
    D_m = (-2/n) * sum(X * (Y - Y_pred)) #derivative m
    D_c = (-2/n) * sum(Y - Y_pred) #derivative c
    m = m - L * D_m  #re-inputting m
    c = c - L * D_c  #re-inputting c
    
print (m, c)

Y_pred = m*X + c
#plotting the regression line
plt.scatter(X, Y) 
plt.plot([min(X), max(X)], [min(Y_pred), max(Y_pred)], color='red')
plt.show()